[package]
name = "datediff"
version = "0.1.0"
authors = ["Matthew Klein <mklein994@gmail.com>"]

[dependencies]
chrono = "0.4.0"
chrono-humanize = "0.0.11"
clap = { version = "2.29.2", features = ["wrap_help"] }
